<?php

/**
 * @file
 * Primary module hooks for levchik module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function levchik_theme($existing, $type, $theme, $path) {
  return [
    'levchik_theme_hook' => [
      'variables' => [
        'cats' => NULL,
      ],
      'template' => 'cats-item',
    ],
    'levchik_cats_button' => [
      'variables' => [
        'id' => NULL,
      ],
      'template' => 'cats-buttons',
    ],
  ];
}

